# Generated by Django 5.2.9 on 2026-06-24 08:33

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='netbox_rack_design.designgroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'design group',
                'verbose_name_plural': 'design groups',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(blank=True, db_index=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_designs', to='netbox_rack_design.design')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='netbox_rack_design.design')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='netbox_rack_design.design')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_designs', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='netbox_rack_design.designgroup')),
            ],
            options={
                'verbose_name': 'design',
                'verbose_name_plural': 'designs',
                'ordering': ('site', 'sequence', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DesignPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kind', models.CharField(max_length=20)),
                ('proposed_name', models.CharField(blank=True, max_length=64)),
                ('target_position', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('target_face', models.CharField(blank=True, max_length=10)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='netbox_rack_design.design')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_placements', to='dcim.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='design_placements', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_placements', to='dcim.rack')),
            ],
            options={
                'verbose_name': 'design placement',
                'verbose_name_plural': 'design placements',
                'ordering': ('design', 'target_position', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='design',
            constraint=models.UniqueConstraint(fields=('root', 'version'), name='netbox_rack_design_design_unique_root_version'),
        ),
    ]
