# Generated by Django 5.2.9 on 2026-06-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0002_designplacement_device_role_designplacement_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_design_favorite_device_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorite device type',
                'verbose_name_plural': 'favorite device types',
                'ordering': ('user', 'device_type'),
                'constraints': [models.UniqueConstraint(fields=('user', 'device_type'), name='netbox_rack_design_favoritedevicetype_unique_user_device_type')],
            },
        ),
    ]
