# Generated by Django 5.2.9 on 2026-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0003_favoritedevicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='racks',
            field=models.ManyToManyField(blank=True, related_name='scoped_designs', to='dcim.rack'),
        ),
    ]
