# Generated by Django 5.2.9 on 2026-06-27 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0005_seed_design_racks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenDesignRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_rack_states', to='netbox_rack_design.design')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_design_hidden_racks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hidden design rack',
                'verbose_name_plural': 'hidden design racks',
                'ordering': ('user', 'design', 'rack'),
                'constraints': [models.UniqueConstraint(fields=('user', 'design', 'rack'), name='netbox_rack_design_hiddendesignrack_unique_user_design_rack')],
            },
        ),
    ]
