# Generated by Django 5.2.9 on 2026-07-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0006_hiddendesignrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='power_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='power_source_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='real_power_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.powerfeed'),
        ),
        migrations.CreateModel(
            name='DesignPowerFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('voltage', models.PositiveIntegerField(default=230)),
                ('amperage', models.PositiveIntegerField(default=16)),
                ('phase', models.CharField(default='single-phase', max_length=20)),
                ('supply', models.CharField(default='ac', max_length=20)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_feeds', to='netbox_rack_design.design')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack')),
            ],
            options={
                'verbose_name': 'design power feed',
                'verbose_name_plural': 'design power feeds',
                'ordering': ('design', 'rack', 'name'),
            },
        ),
        migrations.AddField(
            model_name='designplacement',
            name='planned_power_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_placements', to='netbox_rack_design.designpowerfeed'),
        ),
        migrations.CreateModel(
            name='DesignRackPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('power_config', models.JSONField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_power', to='netbox_rack_design.design')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack')),
            ],
            options={
                'verbose_name': 'design rack power',
                'verbose_name_plural': 'design rack power',
                'ordering': ('design', 'rack'),
            },
        ),
        migrations.AddConstraint(
            model_name='designpowerfeed',
            constraint=models.UniqueConstraint(fields=('design', 'rack', 'name'), name='netbox_rack_design_designpowerfeed_unique_design_rack_name'),
        ),
        migrations.AddConstraint(
            model_name='designrackpower',
            constraint=models.UniqueConstraint(fields=('design', 'rack'), name='netbox_rack_design_designrackpower_unique_design_rack'),
        ),
    ]
