# Generated by Django 5.2.9 on 2026-08-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0007_designplacement_power_config_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='parent_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bay_children', to='netbox_rack_design.designplacement'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='target_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_placements', to='dcim.devicebay'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='target_bay_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='designplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('target_bay__isnull', False)), fields=('design', 'target_bay'), name='netbox_rack_design_designplacement_unique_design_target_bay'),
        ),
        migrations.AddConstraint(
            model_name='designplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_placement__isnull', False)), fields=('design', 'parent_placement', 'target_bay_name'), name='netbox_rack_design_designplacement_unique_design_planned_bay'),
        ),
    ]
