# Generated by Django 5.2.9 on 2026-08-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0008_designplacement_parent_placement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenDesignChassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.device')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_chassis_states', to='netbox_rack_design.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_design_hidden_chassis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hidden design chassis',
                'verbose_name_plural': 'hidden design chassis',
                'ordering': ('user', 'design', 'chassis'),
                'constraints': [models.UniqueConstraint(fields=('user', 'design', 'chassis'), name='netbox_rack_design_hiddendesignchassis_unique_user_design_chassis')],
            },
        ),
    ]
