"""Named favorite SETS: a user keeps several starred-device-type lists.

Hand-written rather than autogenerated because the new ``favorite_set`` FK is
non-null on a table that already has rows: existing favorites are moved into a
per-user set named "Default" between adding the column and tightening it, so a
user's stars survive the upgrade exactly as they were.

The uniqueness moves with them: a device type used to be starrable once per
user, and is now starrable once per SET (so it can sit in "for server" and
"for network" at the same time).
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEFAULT_NAME = "Default"


def move_favorites_into_a_default_set(apps, schema_editor):
    """Give every user with existing stars a "Default" set holding them."""
    FavoriteSet = apps.get_model("netbox_rack_design", "FavoriteSet")
    FavoriteDeviceType = apps.get_model("netbox_rack_design", "FavoriteDeviceType")

    user_ids = (
        FavoriteDeviceType.objects.filter(favorite_set__isnull=True)
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in list(user_ids):
        fav_set, _created = FavoriteSet.objects.get_or_create(
            user_id=user_id, name=DEFAULT_NAME
        )
        FavoriteDeviceType.objects.filter(
            user_id=user_id, favorite_set__isnull=True
        ).update(favorite_set=fav_set)


def unset_favorite_sets(apps, schema_editor):
    """Reverse: drop the sets, leaving the favorites as one flat per-user list.

    Rows that were duplicated ACROSS sets collapse back to one per user and
    device type -- the pre-set schema cannot represent them twice -- so the
    extra copies are deleted here rather than failing the constraint below.
    """
    FavoriteSet = apps.get_model("netbox_rack_design", "FavoriteSet")
    FavoriteDeviceType = apps.get_model("netbox_rack_design", "FavoriteDeviceType")

    seen = set()
    doomed = []
    for fav in FavoriteDeviceType.objects.order_by("pk"):
        key = (fav.user_id, fav.device_type_id)
        if key in seen:
            doomed.append(fav.pk)
        else:
            seen.add(key)
    if doomed:
        FavoriteDeviceType.objects.filter(pk__in=doomed).delete()
    FavoriteDeviceType.objects.update(favorite_set=None)
    FavoriteSet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_rack_design", "0009_hiddendesignchassis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_design_favorite_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite set",
                "verbose_name_plural": "favorite sets",
                "ordering": ("user", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="netbox_rack_design_favoriteset_unique_user_name",
                    )
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="favoritedevicetype",
            name="netbox_rack_design_favoritedevicetype_unique_user_device_type",
        ),
        migrations.AddField(
            model_name="favoritedevicetype",
            name="favorite_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="netbox_rack_design.favoriteset",
            ),
        ),
        migrations.RunPython(
            move_favorites_into_a_default_set, unset_favorite_sets
        ),
        migrations.AlterField(
            model_name="favoritedevicetype",
            name="favorite_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="netbox_rack_design.favoriteset",
            ),
        ),
        migrations.AlterModelOptions(
            name="favoritedevicetype",
            options={
                "ordering": ("user", "favorite_set", "device_type"),
                "verbose_name": "favorite device type",
                "verbose_name_plural": "favorite device types",
            },
        ),
        migrations.AddConstraint(
            model_name="favoritedevicetype",
            constraint=models.UniqueConstraint(
                fields=("favorite_set", "device_type"),
                name="netbox_rack_design_favoritedevicetype_unique_set_device_type",
            ),
        ),
    ]
