# Generated by Django 5.2.9 on 2026-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_design', '0011_designpowerfeed_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='planning_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
