# Generated by Django 5.2.9 on 2026-09-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0012_designplacement_planning_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='stale_device_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_placements', to='dcim.device'),
        ),
    ]
