# Generated by Django 5.2.9 on 2026-09-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_design', '0013_designplacement_stale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='base_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_placements', to='netbox_rack_design.designplacement'),
        ),
    ]
