# Generated by Django 5.2.9 on 2026-09-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0014_designplacement_base_placement'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='base_parent_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_bay_children', to='netbox_rack_design.designplacement'),
        ),
        migrations.AddConstraint(
            model_name='designplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('base_parent_placement__isnull', False)), fields=('design', 'base_parent_placement', 'target_bay_name'), name='netbox_rack_design_designplacement_unique_design_base_parent_bay'),
        ),
    ]
