# Generated by Django 5.2.9 on 2026-09-07 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0015_designplacement_base_parent_placement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('design_title', models.CharField(blank=True, max_length=200)),
                ('device_name', models.CharField(blank=True, max_length=64)),
                ('prior_device_status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applies', to='netbox_rack_design.design')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applies', to='netbox_rack_design.designplacement')),
            ],
            options={
                'verbose_name': 'design apply',
                'verbose_name_plural': 'design applies',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('placement__isnull', False)), fields=('placement',), name='netbox_rack_design_designapply_unique_placement')],
            },
        ),
    ]
