# Generated by Django 5.2.9 on 2026-09-12 11:38

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0016_designapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('u_height', models.PositiveSmallIntegerField(default=42)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_racks', to='dcim.location')),
                ('realized_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.rack')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'planned rack',
                'verbose_name_plural': 'planned racks',
                'ordering': ('location', 'name'),
                'constraints': [models.UniqueConstraint(fields=('location', 'name'), name='netbox_rack_design_plannedrack_unique_location_name')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
