# Generated by Django 5.2.9 on 2026-09-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0017_plannedrack'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='planned_racks',
            field=models.ManyToManyField(blank=True, related_name='scoped_designs', to='netbox_rack_design.plannedrack'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='target_planned_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_placements', to='netbox_rack_design.plannedrack'),
        ),
        migrations.AddConstraint(
            model_name='designplacement',
            constraint=models.CheckConstraint(condition=models.Q(('target_rack__isnull', True), ('target_planned_rack__isnull', True), _connector='OR'), name='netbox_rack_design_designplacement_single_target_rack'),
        ),
    ]
