# Generated by Django 5.2.9 on 2026-09-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0018_design_planned_racks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designpowerfeed',
            options={'ordering': ('design', 'rack', 'planned_rack', 'name')},
        ),
        migrations.AlterModelOptions(
            name='designrackpower',
            options={'ordering': ('design', 'rack', 'planned_rack')},
        ),
        migrations.RemoveConstraint(
            model_name='designpowerfeed',
            name='netbox_rack_design_designpowerfeed_unique_design_rack_name',
        ),
        migrations.RemoveConstraint(
            model_name='designrackpower',
            name='netbox_rack_design_designrackpower_unique_design_rack',
        ),
        migrations.AddField(
            model_name='designpowerfeed',
            name='planned_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='netbox_rack_design.plannedrack'),
        ),
        migrations.AddField(
            model_name='designrackpower',
            name='planned_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='netbox_rack_design.plannedrack'),
        ),
        migrations.AlterField(
            model_name='designpowerfeed',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack'),
        ),
        migrations.AlterField(
            model_name='designrackpower',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack'),
        ),
        migrations.AddConstraint(
            model_name='designpowerfeed',
            constraint=models.UniqueConstraint(condition=models.Q(('rack__isnull', False)), fields=('design', 'rack', 'name'), name='netbox_rack_design_designpowerfeed_unique_design_rack_name'),
        ),
        migrations.AddConstraint(
            model_name='designpowerfeed',
            constraint=models.UniqueConstraint(condition=models.Q(('planned_rack__isnull', False)), fields=('design', 'planned_rack', 'name'), name='netbox_rack_design_designpowerfeed_unique_design_planned_rack_name'),
        ),
        migrations.AddConstraint(
            model_name='designpowerfeed',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('planned_rack__isnull', True), ('rack__isnull', False)), models.Q(('planned_rack__isnull', False), ('rack__isnull', True)), _connector='OR'), name='netbox_rack_design_designpowerfeed_exactly_one_rack'),
        ),
        migrations.AddConstraint(
            model_name='designrackpower',
            constraint=models.UniqueConstraint(condition=models.Q(('rack__isnull', False)), fields=('design', 'rack'), name='netbox_rack_design_designrackpower_unique_design_rack'),
        ),
        migrations.AddConstraint(
            model_name='designrackpower',
            constraint=models.UniqueConstraint(condition=models.Q(('planned_rack__isnull', False)), fields=('design', 'planned_rack'), name='netbox_rack_design_designrackpower_unique_design_planned_rack'),
        ),
        migrations.AddConstraint(
            model_name='designrackpower',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('planned_rack__isnull', True), ('rack__isnull', False)), models.Q(('planned_rack__isnull', False), ('rack__isnull', True)), _connector='OR'), name='netbox_rack_design_designrackpower_exactly_one_rack'),
        ),
    ]
