# Generated by Django 5.2.9 on 2026-09-12 14:13

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0019_alter_designpowerfeed_options_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'template group',
                'verbose_name_plural': 'template groups',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('u_height', models.PositiveSmallIntegerField(default=42)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='netbox_rack_design.templategroup')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ('group', 'order', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TemplatePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('planning_data', models.JSONField(blank=True, null=True)),
                ('face', models.CharField(blank=True, max_length=10)),
                ('anchor', models.CharField(default='top', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('target_bay_name', models.CharField(blank=True, max_length=64)),
                ('device_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicerole')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicetype')),
                ('parent_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bay_children', to='netbox_rack_design.templateplacement')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='netbox_rack_design.template')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'template placement',
                'verbose_name_plural': 'template placements',
                'ordering': ('template', 'order', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('parent_placement__isnull', False)), fields=('template', 'parent_placement', 'target_bay_name'), name='netbox_rack_design_templateplacement_unique_template_planned_bay')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
