# Generated by Django 6.0.8 on 2026-09-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_design', '0020_templategroup_template_templateplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamped_placements', to='netbox_rack_design.template'),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='from_template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
