# Generated by Django 5.2.9 on 2026-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_design', '0021_designplacement_from_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='preferred_feed_legs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
