# Generated by Django 5.2.9 on 2026-09-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0023_design_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpowerfeed',
            name='power_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.powerpanel'),
        ),
    ]
