# Generated by Django 5.2.9 on 2026-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rack_design', '0024_designpowerfeed_power_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateplacement',
            name='offset',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
