# Generated by Django 5.2.9 on 2026-09-28 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_rack_design', '0025_templateplacement_offset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiddendesignrack',
            options={'ordering': ('user', 'design', 'rack', 'planned_rack')},
        ),
        migrations.RemoveConstraint(
            model_name='hiddendesignrack',
            name='netbox_rack_design_hiddendesignrack_unique_user_design_rack',
        ),
        migrations.AddField(
            model_name='hiddendesignrack',
            name='planned_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='netbox_rack_design.plannedrack'),
        ),
        migrations.AlterField(
            model_name='hiddendesignrack',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack'),
        ),
        migrations.AddConstraint(
            model_name='hiddendesignrack',
            constraint=models.UniqueConstraint(condition=models.Q(('rack__isnull', False)), fields=('user', 'design', 'rack'), name='netbox_rack_design_hiddendesignrack_unique_user_design_rack'),
        ),
        migrations.AddConstraint(
            model_name='hiddendesignrack',
            constraint=models.UniqueConstraint(condition=models.Q(('planned_rack__isnull', False)), fields=('user', 'design', 'planned_rack'), name='netbox_rack_design_hiddendesignrack_unique_user_design_planned_rack'),
        ),
        migrations.AddConstraint(
            model_name='hiddendesignrack',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('planned_rack__isnull', True), ('rack__isnull', False)), models.Q(('planned_rack__isnull', False), ('rack__isnull', True)), _connector='OR'), name='netbox_rack_design_hiddendesignrack_one_rack'),
        ),
    ]
