# Generated by Django 5.2.9 on 2026-10-08 10:45

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rack_design', '0026_hiddendesignrack_planned_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='step_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DesignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='netbox_rack_design.design')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'design step',
                'verbose_name_plural': 'design steps',
                'ordering': ('design', 'index'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='netbox_rack_design.designstep'),
        ),
        migrations.AddConstraint(
            model_name='designstep',
            constraint=models.UniqueConstraint(fields=('design', 'index'), name='netbox_rack_design_designstep_unique_design_index'),
        ),
    ]
